// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlp6u8GlU2XZx-fv-VJ4osL1r8upw9nU',
    appId: '1:895180021126:android:0b7afb8227691c1181e007',
    messagingSenderId: '895180021126',
    projectId: 'moorky-ae26f',
    storageBucket: 'moorky-ae26f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayvXv0g7qoIlgj4NE9f4Y62zLKAVyjCw',
    appId: '1:895180021126:ios:1563f656812e7d6481e007',
    messagingSenderId: '895180021126',
    projectId: 'moorky-ae26f',
    storageBucket: 'moorky-ae26f.appspot.com',
    androidClientId: '895180021126-p4gk4qpgijsh8paecfdp7tut5tknji68.apps.googleusercontent.com',
    iosClientId: '895180021126-eg6j0uq0g4t2b8akesbjcq9mnieh2jd5.apps.googleusercontent.com',
    iosBundleId: 'com.moorky.dating.app',
  );
}
